name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: | 
         rsync -av ./ /root/ros2_ws/src/CIT_DAR/
         cd /root/ros2_ws/src
         git clone https://github.com/dynepanch/person_msgs.git
         cd /root/ros2_ws
         rosdep update
         rosdep install -i --from-path src --rosdistro humble -y
         colcon build
         source root/.bashrc
         ros2 interface show person_msgs/msg/Person
         bash -xv ./src/CIT_DAR/CIT_DAR/test/test.bash /root
         
